//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Albums {
    
    private AlbumsAlbum[] albumField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Album")]
    public AlbumsAlbum[] Album {
        get {
            return this.albumField;
        }
        set {
            this.albumField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AlbumsAlbum {
    
    private AlbumsAlbumTrack[] trackField;
    
    private string titleField;
    
    private string artistField;
    
    private System.DateTime releaseDateField;
    
    private decimal averageUserRatingField;
    
    private ushort runtimeField;
    
    private byte priceField;
    
    private ushort tracksField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Track")]
    public AlbumsAlbumTrack[] Track {
        get {
            return this.trackField;
        }
        set {
            this.trackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Artist {
        get {
            return this.artistField;
        }
        set {
            this.artistField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime ReleaseDate {
        get {
            return this.releaseDateField;
        }
        set {
            this.releaseDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal AverageUserRating {
        get {
            return this.averageUserRatingField;
        }
        set {
            this.averageUserRatingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort Runtime {
        get {
            return this.runtimeField;
        }
        set {
            this.runtimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte Price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort Tracks {
        get {
            return this.tracksField;
        }
        set {
            this.tracksField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AlbumsAlbumTrack {
    
    private string titleField;
    
    private string runtimeField;
    
    private string featArtistField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Runtime {
        get {
            return this.runtimeField;
        }
        set {
            this.runtimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FeatArtist {
        get {
            return this.featArtistField;
        }
        set {
            this.featArtistField = value;
        }
    }
}
